# This is a basic workflow to help you get started with Actions

name: IssueCheck

# Controls when the workflow will run
on:
  issues:
    types: [opened, edited]

jobs:
  check-issue-example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      
      # Runs a set of:
      - name: check-issue-example
        run: |
          echo $HELLO
          echo $CHANGES
          echo $ISSUE_ID
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HELO: "HELLO42"
          ISSUE: ${{ toJson(github.event.issue) }}
          CHANGES: ${{ toJson(github.event.changes) }}
          ISSUE_ID: ${{ github.event.issue.id }}

