# This is a basic workflow to help you get started with Actions

name: IssueCheck

# Controls when the workflow will run
on:
  issues:
    types: [opened, edited]

jobs:
  check-issue-example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: run validate.js
        run: |
          pwd
          npm install
          node lint-code-example-in-issues.js
        working-directory: ./lint-example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


